---
title: "Untitled"
format:
  typst:
    fig-format: retina
    mainfont: "Hiragino Mincho ProN"
    number-sections: true
  revealjs:
    incremental: true 
    slide-number: true
    html-math-method: katex
    embed-resources: true
  docx:
    number-sections: true
  pdf:
    number-sections: true
---

# Simple

```{r}
DiagrammeR::grViz("
  digraph {
  rankdir=TB
  P [label='母集団',style=dashed, fontsize=10]
  D [label='データ', fontsize=10]
  S [label='統計量', fontsize=10]
  T [label='推定対象',style=dashed, fontsize=10]
  P -> D [label = 'サンプルング', fontsize=5]
  D -> S [label = '', xlabel = '計算', fontsize=5]
  P -> T [label = '', xlabel = '計算', style=dashed, fontsize=5]
  S -> T [label = '推論',constraint=false, fontsize=5]
  { rank=same; P; D}
  { rank=same; T; S }
  }
  ") |> 
  DiagrammeRsvg::export_svg() |> 
  charToRaw() |> 
  rsvg::rsvg_svg("Diagram/SamplePopulation.svg")
```

# Potential data

```{r}
DiagrammeR::grViz("
  digraph {
  rankdir=TB
  P [label='母集団',style=dashed, fontsize=10]
  D [label='データ', fontsize=10]
  S [label='統計量', fontsize=10]
  T [label='推定対象',style=dashed, fontsize=10]
  D1 [label = 'あり得るデータ',style=dashed, fontsize=10]
  S1 [label = 'あり得る統計量', style=dashed, fontsize=10]
  P -> D [label = 'サンプルング', fontsize=8]
  P -> D1 [constraint=false]
  D -> S [label = '', xlabel = '計算', fontsize=8]
  D1 -> S1 [constraint=false]
  P -> T [label = '', xlabel = '計算', style=dashed, fontsize=8]
  S -> T [label = '推論',constraint=false, fontsize=8]
  S1 -> S [label = '乖離', constraint=false, fontsize=8, dir=both]
  { rank=same; D1; D; P}
  { rank=same; S1; T; S}
  }
  ") |> 
  DiagrammeRsvg::export_svg() |> 
  charToRaw() |> 
  rsvg::rsvg_svg("Diagram/SamplePopulationComplex.svg")
```

# Structure

```{r}
DiagrammeR::grViz("
  digraph {
  rankdir=TB
  M [label='構造',style=dashed,fontsize=10]
  P [label='母集団',style=dashed, fontsize=10]
  D [label='データ', fontsize=10]
  S [label='統計量', fontsize=10]
  T [label='推定対象',style=dashed, fontsize=10]
  D1 [label = 'あり得るデータ',style=dashed, fontsize=10]
  S1 [label = 'あり得る統計量', style=dashed, fontsize=10]
  M -> P [style=dashed]
  P -> D [label = 'サンプルング', fontsize=8]
  P -> D1 [constraint=false]
  D -> S [label = '', xlabel = '計算', fontsize=8]
  D1 -> S1 [constraint=false]
  P -> T [label = '', xlabel = '計算', style=dashed, fontsize=8]
  S -> T [label = '推論',constraint=false, fontsize=8]
  T -> M [constraint=false]
  { rank=same; D1; D; P}
  { rank=same; S1; T; S}
  }
  ") |> 
  DiagrammeRsvg::export_svg() |> 
  charToRaw() |> 
  rsvg::rsvg_svg("Diagram/Structure.svg")
```

