---
title: "Untitled"
format: html
---

# Simple

```{r}
set.seed(111)
library(tidyverse)
library(SuperLearner)
library(hal9001)

data <- read_csv("Public/example.csv") |> 
  mutate(
    Price = Price |> log(),
    CBD = if_else(
      District %in% c(
        "港区",
        "中央区",
        "千代田区"
      ),
      1,
      0
    )
  ) |> 
  filter(
    year_2024 == 1,
    Tenure >= 10
  ) |> 
  select(
    Tenure,
    Price,
    Reform,
    CBD
  )

group <- sample(
  1:3,
  data |> nrow(),
  replace = TRUE
)

data$E_Y_D1 <- SuperLearner(
  Y = data$Price[group == 1 & data$Reform == 1],
  X = data[group == 1 & data$Reform == 1,] |> select(Tenure,CBD),
  newX = data |> select(Tenure,CBD),
  SL.library = list(
    "SL.lm",
    "SL.ranger",
    "SL.hal9001",
    "SL.mean"
  )
  ) |> 
  magrittr::extract2("SL.predict") |> 
  as.numeric()

data$E_Y_D0 <- SuperLearner(
  Y = data$Price[group == 1 & data$Reform == 0],
  X = data[group == 1 & data$Reform == 0,] |> select(Tenure,CBD),
  newX = data |> select(Tenure,CBD),
  SL.library = list(
    "SL.lm",
    "SL.ranger",
    "SL.hal9001",
    "SL.mean"
  )
  ) |> 
  magrittr::extract2("SL.predict") |> 
  as.numeric()

data$E_Y <- SuperLearner(
  Y = data$Price[group == 1],
  X = data[group == 1,] |> select(Tenure,CBD),
  newX = data |> select(Tenure,CBD),
  SL.library = list(
    "SL.lm",
    "SL.ranger",
    "SL.hal9001",
    "SL.mean"
  )
  ) |> 
  magrittr::extract2("SL.predict") |> 
  as.numeric()

data$E_D <- SuperLearner(
  Y = data$Reform[group == 1],
  X = data[group == 1,] |> select(Tenure,CBD),
  newX = data |> select(Tenure,CBD),
  SL.library = list(
    "SL.lm",
    "SL.ranger",
    "SL.hal9001",
    "SL.mean"
  ),
  family = binomial()
  ) |> 
  magrittr::extract2("SL.predict") |> 
  as.numeric()

data$psu_R <- (data$Price - data$E_Y)/(data$Reform - data$E_D)
data$weight_R <- (data$Reform - data$E_D)^2

data$score_ATE <- data$E_Y_D1 - data$E_Y_D0 +
  (data$Reform*(data$Price - data$E_Y_D1)/data$E_D) -
  ((1 - data$Reform)*(data$Price - data$E_Y_D0)/(1 - data$E_D))

data$B_R <- SuperLearner(
  Y = data$psu_R[group == 2],
  X = data[group == 2,] |> select(Tenure,CBD),
  newX = data |> select(Tenure,CBD),
  obsWeights = data$weight_R[group == 2],
  SL.library = list(
    "SL.lm",
    "SL.ranger",
    "SL.hal9001",
    "SL.mean"
  )
  ) |> 
  magrittr::extract2("SL.predict") |> 
  as.numeric()

data$B <- data |> 
  mutate(
    psu_Y = Price - E_Y,
    psu_D = Reform - E_D
  ) |> 
  lm(psu_Y ~ 0 + psu_D, data =_) |> 
  coef() |> 
  as.numeric()

data$B_Linear <- data |> 
  lm(psu_R ~ poly(Tenure,2) + CBD + CBD:Tenure, data =_, subset = group == 2, weights = weight_R) |> 
  predict(data) |> 
  as.numeric()

data$B_Cal <- isoreg(
  data$B_R[group == 3],
  data$score_ATE[group == 3]
) |> 
  as.stepfun() |> 
  apply(data$B_R |> as.matrix(),
        2,
        FUN = _) |> 
  as.numeric()

data |> 
  ggplot(
    aes(
      x = B_R,
      y = B_Cal
    )
  ) +
  geom_line()

data |> 
mutate(
  Y_D1 = E_Y_D1,
  Y_D0 = E_Y_D0,
  Method = "T"
) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B*(1 - E_D),
  Y_D0 = E_Y + B*(0 - E_D),
  Method = "R"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_R*(1 - E_D),
  Y_D0 = E_Y + B_R*(0 - E_D),
  Method = "R Nonpara"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_Cal*(1 - E_D),
  Y_D0 = E_Y + B_Cal*(0 - E_D),
  Method = "R Calibration"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_Linear*(1 - E_D),
  Y_D0 = E_Y + B_Linear*(0 - E_D),
  Method = "R Linear"
  ) 
  ) |> 
  ggplot(
    aes(
      x = Tenure,
      y = Y_D1
    )
  ) +
  geom_line(
    aes(
      linetype = "D1"
    )
  ) +
  geom_line(
    aes(
      y = Y_D0,
      linetype = "D0"
    )
  ) +
  facet_grid(CBD~ Method)

```

```{r}
data |> 
mutate(
  Y_D1 = E_Y_D1,
  Y_D0 = E_Y_D0,
  Method = "T"
) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B*(1 - E_D),
  Y_D0 = E_Y + B*(0 - E_D),
  Method = "R"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_R*(1 - E_D),
  Y_D0 = E_Y + B_R*(0 - E_D),
  Method = "R Nonpara"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_Linear*(1 - E_D),
  Y_D0 = E_Y + B_Linear*(0 - E_D),
  Method = "R Linear"
  ) 
  ) |> 
  bind_rows(
    data |> 
mutate(
  Y_D1 = E_Y + B_Cal*(1 - E_D),
  Y_D0 = E_Y + B_Cal*(0 - E_D),
  Method = "R Cal"
  ) 
  ) |> 
  ggplot(
    aes(
      x = Tenure,
      y = Y_D1 - Y_D0
    )
  ) +
  geom_line(
    aes(
      linetype = "Effect"
    )
  )  +
  facet_grid(CBD~ Method)
```

