---
title: "Untitled"
format:
  typst:
    fig-format: retina
    mainfont: "Hiragino Mincho ProN"
    number-sections: true
execute: 
  message: false
  warning: false
---

# SetUp

- $\mu_{11}=K_{11}\times (1-e)^2$

- $\mu_{01}=K_{11}\times e\times(1-e)$

- $\mu_{10}=K_{11}\times e\times (1-e) + K_{10}\times (1-e)$

- $\mu_{00}=K_{11}\times e^2 + K_{10}\times e + K_{00}$

# Moment

```{r}
library(tidyverse)

data <- read_csv("Data/test_202510106.csv") |> 
  mutate(
    A1 = if_else(Q1 == -50,1,0),
    A2 = if_else(Q2 == 100,1,0)
  )

Mu_11 <- if_else(data$A1 == 1 & data$A2 == 1,1,0) |> mean()

Mu_10 <- if_else(data$A1 == 1 & data$A2 == 0,1,0) |> mean()

Mu_01 <- if_else(data$A1 == 0 & data$A2 == 1,1,0) |> mean()

Mu_00 <- if_else(data$A1 == 0 & data$A2 == 0,1,0) |> mean()

E <- Mu_01/(Mu_11 + Mu_01) 

K_11 <- Mu_11/((1 - E)^2)

K_01 <- (Mu_10 - K_11*(E)*(1 - E))/(1-E)

K_00 <- 0
```


# Bayes

```{r}
library(tidyverse)

data <- read_csv("Data/test_202510106.csv") |> 
  mutate(
    A1 = if_else(Q1 == -50,1,0),
    A2 = if_else(Q2 == 100,1,0)
  )

parameter <- tibble(
  E = seq(0,1,0.05),
  K_11 = seq(0,1,0.05),
  K_10 = seq(0,1,0.05)
  ) |> 
  expand(E,K_11,K_10)

N_11 <- if_else(data$A1 == 1 & data$A2 == 1,1,0) |> sum()

N_10 <- if_else(data$A1 == 1 & data$A2 == 0,1,0) |> sum()

N_01 <- if_else(data$A1 == 0 & data$A2 == 1,1,0) |> sum()

N_00 <- if_else(data$A1 == 0 & data$A2 == 0,1,0) |> sum()

parameter$L <- rep(NA |> as.numeric(),nrow(parameter))

for (i in 1:nrow(parameter)){
  print(i)
  parameter$L[i] <- 
    ((parameter$K_11[i]*(1 - parameter$E[i])*(1 - parameter$E[i]))^N_11)*
    ((parameter$K_11[i]*(1 - parameter$E[i])*parameter$E[i])^N_01)*
    ((parameter$K_11[i]*(1 - parameter$E[i])*parameter$E[i] + 
        parameter$K_10[i]*(1 - parameter$E[i]))^N_10)*
    ((parameter$K_11[i]*parameter$E[i]*parameter$E[i] +
        parameter$K_10[i]*parameter$E[i] + (1 - parameter$K_11[i] - parameter$K_10[i]))^1)
}

parameter[parameter$L == max(parameter$L),]

parameter |> 
  ggplot(
    aes(
      x = K_10,
      y = L
    )
  ) +
  geom_point()

sort(parameter$Post,decreasing = TRUE)[36600]

CI <- parameter |> 
  filter(Post >= 4.508142e-06)

(parameter |> 
    arrange(!L))[1:10]
```


## Adjust

```{r}
library(tidyverse)

data <- read_csv("Data/test.csv") |> 
  mutate(
    A1 = if_else(Q1 == -50,1,0),
    A2 = if_else(Q2 == 100,1,0)
  )

parameter <- tibble(
  E = seq(0,0.5,0.001),
  K_11 = seq(0.5,1,0.001)
  ) |> 
  expand(E,K_11)

N_11 <- if_else(data$A1 == 1 & data$A2 == 1,1,0) |> sum()

N_10 <- if_else(data$A1 == 1 & data$A2 == 0,1,0) |> sum()

N_01 <- if_else(data$A1 == 0 & data$A2 == 1,1,0) |> sum()

N_00 <- if_else(data$A1 == 0 & data$A2 == 0,1,0) |> sum()

parameter$L <- rep(NA |> as.numeric(),nrow(parameter))

for (i in 1:nrow(parameter)){
  print(i)
  parameter$L[i] <- 
    ((parameter$K_11[i]*(1 - parameter$E[i])*(1 - parameter$E[i]))^N_11)*
    ((parameter$K_11[i]*(1 - parameter$E[i])*parameter$E[i])^N_01)*
    ((parameter$K_11[i]*(1 - parameter$E[i])*parameter$E[i] + (1 - parameter$K_11[i])*(1 - parameter$E[i]))^N_10)
}

parameter <- parameter |> 
  mutate(
    Post = L/sum(L)
  )

parameter[parameter$Post == max(parameter$Post),]
```

# ML

Log likelihood is

$$\log(K_{11}\times (1-e)^2)N_{11}+\log(=K_{11}\times e\times(1-e))N_{01}$$

$$+\log(K_{11}\times e\times (1-e) + K_{10}\times (1-e))\times N_{10}$$

$$+\log(K_{11}\times e^2 + K_{10}\times e + K_{00})\times N_{00}$$

$$0=N_{1,0}$$
