---
title: "Untitled"
format: 
  typst:
    fig-format: retina
execute: 
  echo: false
  message: false
  warning: false
  eval: false
---

# Premium

Interest is $$\int Yf(Y\mid d)dY-\int Yf(Y\mid D,X)f(D\mid X)f(X\mid d)dYdDdX$$

# Level

Interest is $$\int Yf(Y\mid D,X)f(D\mid X)f(X\mid d)dYdDdX$$

$$=\int Yf(Y\mid X)f(X\mid d)dYdX$$

Efficient influence function is

$$f(D=d)\phi=I(D=d)E[Y\mid X]$$

$$+(Y-E[Y\mid X])\times f(d\mid X)$$

# R

## Level

```{r}
library(tidyverse)
library(recipes)

arrow::open_dataset(
  "Data/Tokyo_20053_20241.parquet"
)

data <- nanoparquet::read_parquet("Data/Tokyo_20053_20241.parquet") |> 
  mutate(
    Year = 取引時期 |> 
      str_sub(1,4) |> 
      as.numeric(),
    Price = (取引価格/1000000),
    Size = 面積,
    Tenure = 2023 - as.numeric(str_sub(建築年,1,4)),
    Distance = 最寄駅_距離,
    Distict = 市区町村名,
    SRC = if_else(
      建物の構造 == "ＳＲＣ",
      1,
      0
    ),
    Zone = 都市計画,
    Area = 地区名
  ) |> 
  filter(
    Year == 2023,
    種類 == "中古マンション等",
    str_detect(市区町村名,"区")
  ) |> 
  na.omit()

Area <- data |> 
  recipe(~ Zone) |> 
  step_other(
    all_nominal_predictors(),
    threshold = 50
  ) |> 
  prep() |> 
  bake(new_data = NULL)

table(Area$Zone)

Label <- Area$Zone |> 
  unique()

Y <- data$Price |> log()

X <- data |> 
  select(Size,Tenure,Distance,SRC,Distict) |> 
  model.matrix(~ 0 + ., data = _)

E_Y_c_X <- ranger::ranger(
  y = Y,
  x = X
) |> 
  magrittr::extract2("predictions")

Estimation <- function(target) {
  y <- Y
  x <- X
  e_y <- E_Y_c_X
  
  D <- if_else(Area$Zone == target,1,0)
  
  E_D <- D |> mean()
  
  E_D_c_X <- ranger::ranger(
    y = D,
    x = X
  ) |> 
    magrittr::extract2("predictions")
  
  
  Phi = (1/E_D)*(D*Y - D*E_Y_c_X - (Y - E_Y_c_X)*E_D_c_X)
  
  result <- estimatr::lm_robust(Phi ~ 1) |> 
    generics::tidy() |> 
    mutate(
      Type = "Premium",
      Area = target
    )
  
  return(result)
}

Result <- map_dfr(
  1:length(Label),
  function(i){
    Estimation(Label[i])
  }
)

Result |> 
  mutate(
    Area = Area |> fct_reorder(estimate)
  ) |> 
  ggplot(
    aes(
      y = Area,
      x = estimate,
      xmin = conf.low,
      xmax = conf.high
    )
  ) +
  geom_pointrange(
    position = position_dodge(width = 0.5)
  ) +
  theme_bw() +
  geom_vline(
    xintercept = 0
  )
```



## Level

```{r}
library(tidyverse)
library(recipes)

arrow::open_dataset(
  "Data/Tokyo_20053_20241.parquet"
)

data <- nanoparquet::read_parquet("Data/Tokyo_20053_20241.parquet") |> 
  mutate(
    Year = 取引時期 |> 
      str_sub(1,4) |> 
      as.numeric(),
    Price = (取引価格/1000000),
    Size = 面積,
    Tenure = 2023 - as.numeric(str_sub(建築年,1,4)),
    Distance = 最寄駅_距離,
    Distict = 市区町村名,
    SRC = if_else(
      建物の構造 == "ＳＲＣ",
      1,
      0
    ),
    Zone = 都市計画,
    Area = 地区名
  ) |> 
  filter(
    Year == 2023,
    種類 == "中古マンション等",
    str_detect(市区町村名,"区")
  ) |> 
  na.omit()

Area <- data |> 
  recipe(~ Zone) |> 
  step_other(
    all_nominal_predictors(),
    threshold = 50
  ) |> 
  prep() |> 
  bake(new_data = NULL)

table(Area$Zone)

Label <- Area$Zone |> 
  unique()

Y <- data$Price |> log()

X <- data |> 
  select(Size,Tenure,Distance,SRC,Distict) |> 
  model.matrix(~ 0 + ., data = _)

E_Y_c_X <- ranger::ranger(
  y = Y,
  x = X
) |> 
  magrittr::extract2("predictions")


Estimation <- function(target) {
  y <- Y
  x <- X
  e_y <- E_Y_c_X
  
  D <- if_else(Area$Zone == target,1,0)
  
  E_D <- D |> mean()
  
  E_D_c_X <- ranger::ranger(
    y = D,
    x = X
  ) |> 
    magrittr::extract2("predictions")
  
  
  Phi = (1/E_D)*(D*E_Y_c_X + (Y - E_Y_c_X)*E_D_c_X)
  
  result <- estimatr::lm_robust(Phi ~ 1) |> 
    generics::tidy() |> 
    mutate(
      Type = "Counter",
      Area = target
    ) |> 
    bind_rows(
      estimatr::lm_robust(Y ~ 1, subset = D == 1) |> 
    generics::tidy() |> 
    mutate(
      Type = "Actural",
      Area = target
    )
    )
  
  return(result)
}

Result <- map_dfr(
  1:length(Label),
  function(i){
    Estimation(Label[i])
  }
)

Result |> 
  arrange(Area,Type) |> 
  mutate(gap = lag(estimate) - estimate,
         .by = c(Area)) |> 
  mutate(gap = max(gap,na.rm = TRUE),
         .by = c(Area)) |> 
  mutate(
    Area = Area |> fct_reorder(gap)
  ) |> 
  ggplot(
    aes(
      y = Area,
      x = estimate,
      xmin = conf.low,
      xmax = conf.high,
      color = Type
    )
  ) +
  geom_pointrange(
    position = position_dodge(width = 0.5)
  ) +
  theme_bw()
```

