---
title: "Untitled"
format:
  typst:
    fig-format: retina
    mainfont: "Hiragino Mincho ProN"
    number-sections: true
execute: 
  warning: false
  message: false
---

```{r}
library(tidyverse)

n <- 1000

X <- runif(n,0,2)


Y <- X^2 + rnorm(n,0,1)

b0 <--mean(X)/(mean(X^2) - mean(X)^2)

b1 <- 1/(mean(X^2) - mean(X)^2)

((b1*X + b0)*Y) |> mean()

lm(Y ~ X)
```

Estimand is $$\theta=\int \frac{\partial E[Y\mid X]}{\partial X}f(X)dX$$

$$=1$$

## Riesz representation

$$\min \sum (\alpha(X)^2 - 2\frac{\partial \alpha(X)}{\partial X})$$

With linear weight $\alpha(X)=\beta_0+\beta_1X$,

$$\min \sum ([\beta_0+\beta_1X]^2 - 2\beta_1)$$

First order condition is

$$0=\sum [\beta_0+\beta_1X]$$

$$0=\beta_0 + \beta_1\times E[X]$$

and

$$0=\sum ([\beta_0+\beta_1X]X - 1)$$

$$1=\beta_0 E[X]+\beta_1E[X^2]$$

Then,

$$1=-\beta_1E[X]^2+ \beta_1\times E[X^2]$$

$$\frac{1}{E[X^2]-E[X]^2}=\beta_1$$


$$\beta_0 =- \frac{E[X]}{E[X^2]-E[X]^2}$$


```{r}
library(tidyverse)

data("CPS1988", package = "AER")

CPS1988 |> 
  ggplot(
    aes(
      x = experience,
      y = wage
    )
  ) +
  geom_bin2d() +
  stat_summary(geom = "point")

X <- CPS1988$experience

Y <- CPS1988$wage

b0 <--mean(X)/(mean(X^2) - mean(X)^2)

b1 <- 1/(mean(X^2) - mean(X)^2)

((b1*X + b0)*Y) |> mean()

lm(Y~X)
```